services:
  my_blog:
    container_name: my_blog
    working_dir: /usr/src/my_blog
    image: rust:latest
    env_file:
      - ./backend/.env.dev
    volumes:
    - ./backend/:/usr/src/my_blog
    - ./frontend/dist/:/usr/src/my_blog/public
    tty: true
    stdin_open: true
    restart: always
    network_mode: host

  postgres-db:
    container_name: postgres-db
    image: postgres:16
    env_file:
      - ./backend/.env.dev
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/

  frontend:
    container_name: frontend
    image: oven/bun:1.1
    working_dir: /app
    volumes:
      - ./frontend/:/app
    tty: true
    stdin_open: true
    command: "/bin/bash"
    restart: always
    network_mode: host