services:
  postgres-db:
    container_name: postgres-db
    image: postgres:15.1-bullseye
    env_file:
      - ./backend/.env.prod
    network_mode: host
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    restart: unless-stopped

  my_blog:
    container_name: my_blog
    depends_on:
      - postgres-db
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./dist:/dist
    env_file:
      - ./backend/.env.prod
    network_mode: host