version: '3.0'
services:
  my_blog:
    container_name: my_blog
    image: rust:latest
    volumes:
    - ./backend/:/usr/src/my_blog
    tty: true
    stdin_open: true
    restart: always
    network_mode: host

  postgres-db:
    container_name: postgres-db
    image: postgres:15.1-bullseye
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    restart: unless-stopped
    network_mode: host