services:
  my_blog:
    container_name: my_blog
    image: rust:latest
    env_file:
      - ./backend/.env.example
    volumes:
    - ./backend/:/usr/src/my_blog
    - ./frontend/public/:/usr/src/my_blog/public
    tty: true
    stdin_open: true
    restart: always
    network_mode: host

  postgres-db:
    container_name: postgres-db
    image: postgres:15.1-bullseye
    env_file:
      - ./backend/.env.example
    ports:
      - 5432:5432
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/

  frontend:
    container_name: frontend
    image: node:alpine
    volumes:
      - ./frontend/:/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    restart: always
    network_mode: host