FROM node:latest AS interface

WORKDIR /usr/src/app

COPY frontend/package.json frontend/yarn.lock ./

RUN yarn

COPY ./frontend .

RUN yarn build:prod

FROM rust:1.67 as build

WORKDIR /usr/src/my-blog
COPY ./backend .

RUN cargo install --path

FROM alpine:latest as finally

WORKDIR /MyBlog
 
RUN apk update && apk add zip

COPY --from=build /usr/src/my-blog/target .
COPY --from=interface /usr/src/app/build ./public/

RUN zip -r myblog.zip /MyBlog/*

VOLUME /dist/

CMD cp myblog.zip /dist/
